stages:
  - build
  - test 
  - deploy

cache:
  paths: 
    - node_modules/

before_script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl

build job:
  image: node:lts
  stage: build
  script:
  - yarn install
  - yarn build
  artifacts:
    paths:
      - build/

test job:
  image: node:lts
  stage: test
  script: 
  - yarn install
  - yarn test

deploy staging:
  image: ruby:latest
  stage: deploy
  only: 
    - staging
  script:
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
  environment:
    name: staging
    url: https://staging-second-hand-kelompok-5.herokuapp.com/

deploy job:
  stage: deploy
  image: node:lts
  only:
    - main
  environment:
    name: production
    url: https://final-project-binar-kelompok-5.vercel.app/
  script:
    - yarn global add vercel
    - DEPLOYMENT_URL=$(VERCEL_ORG_ID=$VERCEL_ORG_ID VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID vercel --confirm -t $VERCEL_TOKEN --prod)
